[config]
version_check = false

[templates.hyprland]
input_path = "~/.config/noctalia/colorscheme/colors-hyprland.conf"
output_path = "~/.cache/dotfiles/colors_hyprland.conf"
post_hook = "hyprctl reload"
